### ISSUE TITLE
Error compiling for board Arduino/Genuino Mega or Mega 2560

### ISSUE THREAD

**Issue by trevormcinroe** [Freenove/Freenove_Hexapod_Robot_Kit#2]
Hey Freenove team,
I am having issues compiling: Examples > FNHR > Default > Robot

When I hit "Verify", I get the following compilation error:

.../Arduino/libraries/FNHR/FNHRComm.cpp: In member function 'void Communication::StartRF24()':
.../Arduino/libraries/FNHR/FNHRComm.cpp:124:19: error: void value not ignored as it ought to be
   isRF24Available = rf24.begin();

                   ^
exit status 1
Error compiling for board Arduino/Genuino Mega or Mega 2560.

**Comment by trevormcinroe** [comment]
I was able to resolve this issue by removing my previously-existing RF24 library and then adding the version of the RF24 library that is provided in this repo. 

I could be wrong but it looks like this repo relies on an older version of the RF24 library (1.3.3). 
Any confirmation from the repo owner?

**Comment by EthanPal** [comment]
Hi!
There are different RF24 libraries written by different people. Please use the version we provide. 
And you are right we are using (1.3.3). We just launched an update and added the latest version.
The (1.3.3) and latest version are compatible. They are all works fine.
