### ISSUE TITLE
hardware model as blender importable type

### ISSUE THREAD

**Issue by jonnytest1** [Freenove/Freenove_Hexapod_Robot_Kit#3]
i assume FNK0029_Freenove Hexapod Robot Kit_Acrylic.DWG is a 3D model of the robot which i would like to use - however i have searched a bit and not found a free way to convert .dwg files into ones I can use in blender

**Comment by EthanPal** [comment]
Hi! Please don't worry. We will provide help.
We don't know much about Blender, Can you tell me what kind of file is supported?
Please send an email to support@freenove.com. I will close this issue.

**Comment by leahcornelius** [comment]
Hey, did you manage to get a model? I would love for this to be available as well. Thanks 👍🏻 @EthPan @jonnytest1

**Comment by jonnytest1** [comment]
i don think i have oO i found an email chain - but no attachments
